### ISSUE TITLE
Needs a Github Actions build

### ISSUE THREAD

**Issue by dylanwatsonsoftware** [bwobbones/shared_number#1]
Just need to create this file: .github/workflows/android_build.yml

Use this for inspiration:

```
name: Android Build ## name of the workflow

on:
  workflow_dispatch: # To trigger manual build
  push:
  # release:
  #   types: [published] # only run the workflow when a new release has been published

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest # using ubuntu latest version / or you can use a specific version
    steps:
      - name: Check out Git repository # clone the repo to local ci workspace
        uses: actions/checkout@v3

      - name: Set up our JDK environment # setup JDK environment: mandatory as we need to build  android project
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Create google-services.json
        run: 'echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json'
        env:
          GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}

      - run: flutter pub get

      - name: Generate App APK
        run: flutter build apk  --build-name=1.0.${{github.run_number}} --build-number=${{github.run_number}}

      - name: Signing Report
        run: cd android && echo "${{ secrets.ANDROID_KEY_BASE64 }}" | base64 --decode > release.keystore && keytool -list -v -keystore release.keystore -alias resourceful -storepass ${{ secrets.ANDROID_KEYSTORE_PASS }} -keypass ${{ secrets.ANDROID_KEYSTORE_PASS }}

      ## Not required since we just upload to firebase now anyway 
      #- uses: actions/upload-artifact@v3
      #  with:
      #     name: build
      #     path: build/app/outputs/apk/release

      # sign generated apk
      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEY_BASE64 }}
          alias: resourceful
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          keyPassword: ${{ secrets.ANDROID_KEYSTORE_PASS }}

      # Distribute app to Firebase App Distribution for testing / use google play internal track if you have a google play account
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: kidsays
          file: ${{steps.sign_app.outputs.signedReleaseFile}}

      # Run our tests
      # - run: flutter test
      # Analyze our Dart code
      # - run: flutter analyze
```
